import type { RuntimeEdition } from '../library/runtime-schema'
import type { LyricsDocument, TimelineDocument } from '../library/schema'
import type { TimingOverridesDocument } from '../practice/practice-timing-overrides'
import type { buildInfo } from '../release/build-info'

export interface TimingExportSong {
  edition: RuntimeEdition
  lyrics: LyricsDocument
  timeline: TimelineDocument
  overrides: TimingOverridesDocument
}

export type TimingExportBuildInfo = typeof buildInfo

export function createTimingExportFilename(songId?: string): string {
  return songId
    ? `red-repeat-timing-fix-${songId}.md`
    : 'red-repeat-timing-fixes-all.md'
}

export function createTimingExportMarkdown(
  songs: readonly TimingExportSong[],
  metadata: TimingExportBuildInfo,
): string {
  const sortedSongs = [...songs].sort((left, right) =>
    left.edition.song.songId.localeCompare(right.edition.song.songId),
  )
  const sections = sortedSongs.map((song) => createSongExport(song, metadata))
  const machineReadableSongs = sortedSongs.map((song) => ({
    songId: song.edition.song.songId,
    editionContentHash: song.edition.contentHash,
    audioSourceHash: song.edition.audio.sourceHash,
    baseTimelineUrl: song.edition.timelineUrl,
    occurrences: sortOccurrenceFields(song.overrides.occurrences),
  }))
  const machineReadable = machineReadableSongs.length === 1
    ? machineReadableSongs[0]
    : { songs: machineReadableSongs }

  return [
    '# RED:REPEAT Timing Fix Pack',
    '',
    `Generated by RED:REPEAT ${metadata.version} (${metadata.commit}) on ${metadata.environment}.`,
    '',
    '## Codex task',
    '',
    '请在 `MyKr-YSteinsK/red-repeat` 中应用以下 RED:REPEAT 播放切口人工微调。',
    '',
    '只修改下方列出的 `library/<song-id>/timeline.json` 中对应 Occurrence 的唯一 `startMs` / `endMs`。不得修改 Section、lyrics、audioSourceHash 或其他歌曲。保持 source order。应用后运行 `library:validate`、`library:compile`、相关 timing tests、full test、build、`pwa:inspect`。确认新的 Runtime 已消费 canonical timing 后，提交并 push。',
    '',
    '## Changes',
    '',
    ...sections,
    '## Machine-readable timing data',
    '',
    '```json',
    JSON.stringify(machineReadable, null, 2),
    '```',
    '',
  ].join('\n')
}

function createSongExport(
  song: TimingExportSong,
  metadata: TimingExportBuildInfo,
): string {
  const { edition, lyrics, timeline, overrides } = song
  const segmentsById = new Map(lyrics.segments.map((segment) => [segment.id, segment]))
  const sectionsById = new Map(timeline.sections.map((section) => [section.id, section]))
  const occurrenceById = new Map(timeline.occurrences.map((occurrence) => [occurrence.id, occurrence]))
  const entries = Object.entries(overrides.occurrences)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([occurrenceId, fields]) => {
      const occurrence = occurrenceById.get(occurrenceId)
      if (!occurrence) {
        return `### ${occurrenceId}\n\n- canonical occurrence 不在当前 Timeline 中；请先人工复核。\n`
      }
      const segment = segmentsById.get(occurrence.segmentId)
      const section = sectionsById.get(occurrence.sectionId)
      const effectiveStart = fields.startMs ?? occurrence.startMs
      const effectiveEnd = fields.endMs ?? occurrence.endMs
      return [
        `### ${occurrence.id} · ${segment?.lyrics ?? occurrence.segmentId}`,
        '',
        `- section: ${section?.label ?? occurrence.sectionId}`,
        `- source: \`library/${edition.song.songId}/timeline.json\``,
        `- canonical startMs: ${occurrence.startMs}`,
        `- canonical endMs: ${occurrence.endMs}`,
        `- override startMs: ${fields.startMs === undefined ? '未修改' : fields.startMs}`,
        `- override endMs: ${fields.endMs === undefined ? '未修改' : fields.endMs}`,
        `- effective delta: startMs ${effectiveStart - occurrence.startMs >= 0 ? '+' : ''}${effectiveStart - occurrence.startMs}ms; endMs ${effectiveEnd - occurrence.endMs >= 0 ? '+' : ''}${effectiveEnd - occurrence.endMs}ms`,
        '',
      ].join('\n')
    })

  return [
    `### ${edition.song.title} — ${edition.song.artist} (${edition.song.songId})`,
    '',
    `- target source: \`library/${edition.song.songId}/timeline.json\``,
    `- app version: ${metadata.version}`,
    `- build SHA: ${metadata.commit}`,
    `- Edition content hash: ${edition.contentHash}`,
    `- audio source hash: ${edition.audio.sourceHash}`,
    `- canonical Timeline runtime identity: ${edition.timelineUrl}`,
    '',
    ...entries,
  ].join('\n')
}

function sortOccurrenceFields(
  occurrences: TimingOverridesDocument['occurrences'],
): TimingOverridesDocument['occurrences'] {
  return Object.fromEntries(
    Object.entries(occurrences)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([occurrenceId, fields]) => [
        occurrenceId,
        Object.fromEntries(
          Object.entries(fields).sort(([left], [right]) => left.localeCompare(right)),
        ),
      ]),
  )
}
