export type ReleaseLevel = 'patch' | 'minor' | 'major'

export interface ReleaseNote {
  version: string
  date: string
  commit: string
  level: ReleaseLevel
  title: string
  summary: string
  changes: readonly string[]
}

// Ordered by the real release history, newest first. This is a product ledger,
// not a Plan index: several commits are intentionally represented by one entry,
// while user-visible fixes can have their own patch node.
export const RELEASES: readonly ReleaseNote[] = [
  {
    version: '1.10.0',
    date: '2026-08-28',
    commit: '426069c',
    level: 'minor',
    title: '《NIGHT DANCER》新曲正式导入',
    summary: '将 imase《NIGHT DANCER》作为第三首公开 Song Edition 导入 Production。',
    changes: [
      '新增完整的 34 个 canonical Segment、49 个 sung Occurrence、11 个 Section、11 个 Practice Unit 与 6 篇 Explain Feature。',
      '整合 34/34 ruby 与 Romaji、用户翻译和 8 个高价值 lyric notes，并保留受保护的 部屋 与 あぁ あぁ 愛して 内容。',
      '使用精确 MP3/JPEG 资产与统一 startMs/endMs Provisional Timing，不引入 schema、compiler、runtime、UI 或 PWA 生命周期改动。',
    ],
  },
  {
    version: '1.9.2',
    date: '2026-08-28',
    commit: '449e3ce',
    level: 'patch',
    title: '《千本桜》全歌词罗马音完整补齐',
    summary: '为《千本桜》全部 30 个 canonical Segment 补齐可直接用于学唱的 Romaji layer。',
    changes: [
      '为 s001–s030 全部 30 个唯一 Segment 添加一个非空 Romaji layer，并保留 ruby、歌词、translation 与 notes。',
      '沿用现有 WORK Romaji 风格，覆盖片假名拼写、特殊读音、助词、长音和 ICBM 混合 Latin token。',
      '保持 Occurrence、timing、Practice、Section、audio、schema、compiler、runtime 与 UI 不变。',
    ],
  },
  {
    version: '1.9.1',
    date: '2026-08-28',
    commit: '3cd207e',
    level: 'patch',
    title: '移动端歌词布局与底部控制层校正',
    summary: '修复窄屏歌词左侧阅读锚点、Practice 尾部可达性和 Practice / Full Song / Timing Debugger 控制层的玻璃与贴边几何。',
    changes: [
      '恢复 Practice 与 Full Song 歌词内容簇的稳定左侧阅读轴，保留 ruby、翻译、点击目标和换行对齐。',
      '用基于 fixed dock 实测高度和最终行可达性的最小 reserve 替代 Practice 完整 dock 高度留白。',
      '降低控制层背景 alpha 并提供显式 fallback，统一 Practice、Full Song 与 Timing Debugger 的轻量 glass surface；移动 Timing Debugger 改为 safe-area 内收的 edge-to-edge bottom sheet。',
    ],
  },
  {
    version: '1.9.0',
    date: '2026-08-28',
    commit: 'a006304',
    level: 'minor',
    title: '统一 Occurrence 时序模型',
    summary: '将 Occurrence 的双 timing 收敛为一个由人工校准值驱动的权威 startMs/endMs 区间，并让解析、高亮与播放共享同一时序边界。',
    changes: [
      '将两个公开 Song Edition 的 106 个 Occurrences 从旧 playback pair 精确迁移到单一 startMs/endMs，保留《千本桜》45/45 人工校准值。',
      '统一 Resolver、Practice、Full Song、Explain 与 Timing Debugger 的 effective timing 消费路径，移除 active contract 中的 playStartMs/playEndMs。',
      '将 identity-bound local timing overrides 升级为 schema v3 的同字段 sparse overlay，并将 Timing Correction Export 收敛为 single-pair contract。',
    ],
  },
  {
    version: '1.8.2',
    date: '2026-08-28',
    commit: 'cbb3bd0',
    level: 'patch',
    title: '歌词注解与 Explain 知识内容升级',
    summary: '升级两首公开 Song Edition 的 Explain 文章与歌词注解，补充可核对的文化、语言和作品背景信息。',
    changes: [
      '《千本桜》Explain 从 4 篇扩展为 6 篇，并保留 9 个经审核的高价值 note target。',
      '《Ｗ●ＲＫ》6 篇 Explain 全部替换为 reviewed version，更新 18 个歌词 note。',
      '保持 translation、canonical Japanese lyrics、ruby、timing、Practice、Section、audio 与 UI/runtime 不变。',
    ],
  },
  {
    version: '1.8.1',
    date: '2026-08-28',
    commit: '91b703a',
    level: 'patch',
    title: '曲库、讲解与封面交互整理',
    summary: '简化曲库和讲解入口，并支持在 Song Edition 中放大查看封面。',
    changes: [
      '曲库卡片聚焦歌曲信息，移除学习状态文案并停止目录层 resume summary 读取。',
      '降低讲解标题层级，保留歌词引用试听和重复出现位置选择，移除“学习这一段”入口。',
      '放大 Song Edition 顶部封面，并支持使用高质量封面在居中 overlay 中查看。',
    ],
  },
  {
    version: '1.8.0',
    date: '2026-08-28',
    commit: '01cdd64',
    level: 'minor',
    title: '移动端播放与歌词阅读体验修复',
    summary: '收紧移动端播放控制与歌词阅读主链，让学唱、全曲和 Timing Debugger 在窄屏下更易阅读和跟随。',
    changes: [
      '将 Timing Debugger 移动端控制台收拢为实际 dock geometry，移除半屏级硬编码预留并保留安全区避让。',
      '让 Practice 连续播放与渐速播放的当前歌词跟随 Resolver primary occurrence，同时保持 persisted resume 与 canonical timing 不变。',
      '修正 Full Song 器乐段 marker 的独立视觉 signal，并将 Practice / Full Song 歌词内容簇改为整体居中、内部左对齐。',
    ],
  },
  {
    version: '1.7.2',
    date: '2026-08-28',
    commit: '50e7114',
    level: 'patch',
    title: '《千本桜》人工播放切口校准',
    summary: '将用户在 Production Timing Debugger 中逐句确认的播放切口合入 canonical source。',
    changes: [
      '合入 45 个 Occurrences 的 82 个 playStartMs/playEndMs 校准值。',
      '保留 startMs/endMs、Occurrence 顺序、歌词、音频与其他歌曲数据不变。',
    ],
  },
  {
    version: '1.7.1',
    date: '2026-08-28',
    commit: 'a98e300',
    level: 'patch',
    title: '《Ｗ●ＲＫ》封面、翻译与 Explain 刷新',
    summary: '更新《Ｗ●ＲＫ》封面和 61 条中文译文，并扩展作品背景、制作与歌词解读内容。',
    changes: [
      '使用新的 1280×1280 JPEG 封面，移除旧 SVG 封面。',
      '替换 61 条中文 translation；保留 canonical Japanese lyrics、ruby、音频、结构和 timing。',
      '将 WORK Explain 从 2 篇扩展为 6 篇，补充作品背景、制作阵容、语言、主题与对位阅读。',
    ],
  },
  {
    version: '1.7.0',
    date: '2026-08-27',
    commit: '325d418',
    level: 'minor',
    title: '《千本桜》Song Edition 正式导入',
    summary: '新增第二个公开 Song Edition，完成《千本桜》的歌词、振假名、Explain 内容、练习分段与音频时序校准。',
    changes: [
      '新增 30 个可复用 Segment、45 个演唱 Occurrence 和 6 个 Practice Unit，保留重复歌词的独立演唱位置。',
      '为日文 canonical lyrics 补充位置可验证的 Hiragana ruby，并提供四篇作品背景与学唱观察。',
      '基于 canonical MP3 的局部声学证据建立独立 actual timing 与 playback range，覆盖长间奏、再入、副歌回返和尾奏边界。',
    ],
  },
  {
    version: '1.6.2',
    date: '2026-08-25',
    commit: 'c61f977',
    level: 'patch',
    title: '歌曲切段边界修正',
    summary: '收紧《WORK》歌曲的播放切段，减少相邻音节串入和过度留白，让学唱、全曲与讲解中的听感更贴合歌词边界。',
    changes: [
      '收紧快速段、重复副歌与尾句的播放起止点，减少前后句音节泄漏和不必要的空白。',
      '让播放区间可独立于歌词高亮区间精确表达真实演唱边界。',
      '保留真实连唱、叠唱、对位和延音，不以统一 padding 强行截短歌曲。',
    ],
  },
  {
    version: '1.6.1',
    date: '2026-08-25',
    commit: '4cfe378',
    level: 'patch',
    title: '播放器玻璃层与切段体验修复',
    summary: '修复移动播放器的控件比例、玻璃透视和底部遮挡，并让学唱与讲解切换不再经过黑闪动画路径。',
    changes: [
      '学唱移动控制行恢复三档速度与适中播放键的真实顺序，底栏改为四角内收浮层，并按实际高度计算内容留白。',
      'Practice 与 Full Song 共享 72% 半透明玻璃材质，恢复 backdrop blur，同时放大全曲播放键并抬高底部操作。',
      '移除原生 View Transition，学唱所有切段入口统一即时定位到新段标题，讲解保留原有锚点与翻页滚动语义。',
    ],
  },
  {
    version: '1.6.0',
    date: '2026-08-25',
    commit: '7039a15',
    level: 'minor',
    title: '播放器复原与稳定切换',
    summary: '恢复播放器专属体验，收口学唱段落选择，并让 Practice 与 Explain 的内容切换稳定可预测。',
    changes: [
      '恢复 Full Song 独立播放器 surface，播放按钮并入速度行，移动端高度与安全区留白重新收紧。',
      '删除正文歌曲地图，学唱改为上一段、当前段、下一段与固定上拉 Segment Picker。',
      '统一 Practice 与 Explain 的锚点保持、内容起点 reveal、reduced-motion 和 View Transition fallback。',
    ],
  },
  {
    version: '1.5.0',
    date: '2026-08-25',
    commit: '598b384',
    level: 'minor',
    title: '统一圆角控件与整宽学唱控制层',
    summary: '建立一致的正式控件语言，并让移动学唱与全曲播放器共享整宽、通透的底部控制层。',
    changes: [
      '新增圆角、尺寸、间距和状态 token，只为正式操作控件接入 control-button，保留歌词、列表和微操作的无框语义。',
      '学唱控制器改为贴合屏幕三边的整宽半透明底部层，安全区内收且顶部圆角、模糊和阴影统一。',
      '全曲播放器、讲解翻页与歌词引用、设置和更新入口统一控件状态，并补充非控件边界回归测试。',
    ],
  },
  {
    version: '1.4.2',
    date: '2026-08-24',
    commit: '58385d3',
    level: 'patch',
    title: '学唱与讲解控制器视觉纠偏',
    summary: '统一高频控制区的浮层、圆角、留白和状态层级，让移动练习与讲解翻页更像完整产品。',
    changes: [
      '学唱控制器改为高可读的半透明圆角浮层，补足屏幕边距、卡片内边距与柔和阴影。',
      '重新平衡上下段、当前段、播放、速度与练习模式三行栅格，主操作和红色选中态更清晰。',
      '讲解底部翻页收拢为对称的圆角操作组，移动端与桌面端都保持饱满且稳定的点击区域。',
    ],
  },
  {
    version: '1.4.1',
    date: '2026-08-24',
    commit: '61fdcb5',
    level: 'patch',
    title: '学唱地图与底部工作台体验',
    summary: '让学唱地图、浮动工作台、讲解翻页和曲库状态在移动端更稳定、更轻。',
    changes: [
      '学唱工作台改为带安全间距的近白半透明浮动底栏，歌词末端不再留下过量空白。',
      '歌曲地图提升移动端可视高度并独立滚动，切段时只在地图内部跟焦，避免整页跳动。',
      '讲解底部导航重排为上一篇、回到顶部、下一篇，已下载状态改为轻量文字标识。',
    ],
  },
  {
    version: '1.4.0',
    date: '2026-08-24',
    commit: '5e37fae',
    level: 'minor',
    title: '学唱控制器与曲库滑动操作',
    summary: '收紧学唱高频控制，并让已下载歌曲通过轻量左滑完成删除。',
    changes: [
      '学唱控制器收口为上下文、播放速度和模式三行，移动端不再需要展开半屏控制器。',
      '连续播放与渐速练习使用清晰的红底选中态，速度选择在渐速开启时保留语义并降低视觉干扰。',
      '曲库下载状态移入标题行 micro-slot，已下载歌曲通过左滑删除，纵向滚动和歌曲导航保持独立。',
    ],
  },
  {
    version: '1.3.1',
    date: '2026-08-24',
    commit: '6197de9',
    level: 'patch',
    title: '发布链与版本探针可靠性',
    summary: '让 Pages 发布、构建身份和应用内更新检查围绕同一个可验证的生产构建闭环运行。',
    changes: [
      'CI 质量检查与 Pages 部署合并为同一条链，并在部署后等待线上 version.json 与本次 commit 收敛。',
      'version.json 现在记录 builtAt，探针固定使用 origin 与部署 BASE_URL，避免路由和旧缓存误判。',
      '设置页展示线上版本、Build SHA、构建时间和最近检查结果；失败时不再残留“最新版本”状态。',
    ],
  },
  {
    version: '1.3.0',
    date: '2026-08-24',
    commit: '7b03b19',
    level: 'minor',
    title: '移动曲库卡片紧凑重排',
    summary: '首页歌曲列表收敛为紧凑的横向作品记录，移动端更易扫读且操作保持在同一行。',
    changes: [
      '缩小移动端封面，稳定标题、歌手、元信息和学习 CTA 的信息栈高度。',
      '将下载状态与下载/移除操作并入卡片右侧，删除低价值的跳转箭头。',
      '为长标题、长歌手和各类本机下载状态补充卡片边界回归覆盖。',
    ],
  },
  {
    version: '1.2.6',
    date: '2026-08-24',
    commit: 'a308045',
    level: 'patch',
    title: 'PWA 注册时序竞态收尾',
    summary: '一键更新会等待 Service Worker registration 就绪，不再因注册回调晚到而丢失激活请求。',
    changes: [
      '修复版本探针和注册回调竞速时立即更新进入 updating 后无法继续的问题。',
      'registration 就绪后自动继续既有的更新、等待、跳过等待和单次刷新流程。',
      '新增延迟 onRegisteredSW 回调的精确顺序回归测试。',
    ],
  },
  {
    version: '1.2.5',
    date: '2026-08-24',
    commit: '84a9a93',
    level: 'patch',
    title: 'PWA Worker 接管收口',
    summary: '更新会等待新版 Worker 真正就绪，并在激活完成后可靠接管页面。',
    changes: [
      '修复远端版本探针先到时需要再次点击立即更新的问题。',
      '新版 Worker 激活后即使缺少 controllerchange 回调也能完成单次刷新。',
      '保留可恢复超时，并让更新后的页面继续使用当前 PWA 缓存。',
    ],
  },
  {
    version: '1.2.4',
    date: '2026-08-24',
    commit: '49e1fe3',
    level: 'patch',
    title: 'PWA 更新竞态与远端说明修复',
    summary: 'PWA 会等待新版 Service Worker 真正可激活，并在更新前展示远端真实更新说明。',
    changes: [
      '修复 version probe 先于 waiting worker 到达时需要重复点击更新的问题。',
      '更新前显示由唯一 release ledger 自动生成的远端版本说明。',
      '“稍后”在当前 App 会话内保持静默，更高版本仍会重新提示。',
    ],
  },
  {
    version: '1.2.3',
    date: '2026-08-24',
    commit: '8eaf6e6',
    level: 'patch',
    title: '更新检查响应修复',
    summary: 'Settings 的版本探针不再被异常卡住的 Service Worker 更新请求阻塞。',
    changes: [
      '版本探针与 Service Worker 更新检查解耦，手动检查可以及时返回状态。',
      '一键更新对 Service Worker 更新请求增加有限等待，保留等待接管与单次刷新语义。',
    ],
  },
  {
    version: '1.2.2',
    date: '2026-08-24',
    commit: 'cad4665',
    level: 'patch',
    title: '下载状态持久化修复',
    summary: '用户下载的歌曲 Runtime 资源现在会完整写入专用下载 cache，并在应用更新后继续可识别。',
    changes: [
      '修复 Service Worker 已缓存普通 Runtime 资源时下载 manifest 不完整的问题。',
      '更新后保留已下载歌曲的可识别状态，不改变现有 Runtime cache contract。',
    ],
  },
  {
    version: '1.2.1',
    date: '2026-08-23',
    commit: 'e9e1ca9',
    level: 'patch',
    title: 'Settings 手动检查更新',
    summary: 'Settings 现在可以手动检查生产构建，并从更新入口直接回到对应的更新日志里程碑。',
    changes: [
      '新增当前版本、手动检查更新和立即更新操作。',
      '全局查看更新入口会突出并展开对应的更新日志里程碑。',
      '保留非阻塞更新提示与 Service Worker 一键接管语义。',
    ],
  },
  {
    version: '1.2.0',
    date: '2026-08-23',
    commit: '4a8b5b6',
    level: 'minor',
    title: 'PWA 一键更新',
    summary: '安装后的 RED:REPEAT 会主动发现生产新构建，并把更新决定交给用户。',
    changes: [
      '新增全局新版提示、稍后隐藏和查看更新入口。',
      '支持通过 waiting Service Worker 一键激活并刷新到新构建。',
      '新增不会进入 App Shell precache 的生产 version.json 探针。',
    ],
  },
  {
    version: '1.1.0',
    date: '2026-08-23',
    commit: '386fdbe',
    level: 'minor',
    title: '语义版本与里程碑更新日志',
    summary: '版本开始按真实 commit 语义记录，更新日志按里程碑归档并支持待归档 patch 独立浏览。',
    changes: [
      '建立唯一 release ledger、SemVer 规则和可验证的 Git tag 工作流。',
      '更新日志以 1.1、1.0 等里程碑分组，展开后直接展示阶段内所有版本。',
      '下一个里程碑产生前的 patch 会独立显示，并在新 milestone 出现后自动归档。',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-08-23',
    commit: '4f9ebd1',
    level: 'major',
    title: 'RED:REPEAT 1.0',
    summary: '收口为适合长期使用的固定产品模式，并建立从人工 timing 到 Codex source 修复的闭环。',
    changes: [
      'Practice 简化为单句、连续、渐速和 0.60x / 0.80x / 1.00x。',
      'Full Song 收口播放跟随、器乐段、回顶部和重置语义。',
      '新增 Settings、系统信息、播放切口调试和 Codex 微调导出。',
      '统一 Practice、Full Song、Explain 的 Effective Timing，并在 Edition 更新后自动清理旧微调。',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-08-23',
    commit: 'e95ad0b',
    level: 'patch',
    title: '全曲标签层级修复',
    summary: '修复全曲模式中标签与固定播放器的层级关系。',
    changes: ['让 Full Song tabs 在固定播放器上方保持可达。'],
  },
  {
    version: '0.9.0',
    date: '2026-08-23',
    commit: '3d7e053',
    level: 'minor',
    title: '公开曲库与安装体验',
    summary: '把真实曲库、GitHub Pages、离线下载和正式 PWA 图标接入公开产品壳。',
    changes: [
      '公开 library/ 成为正式 Runtime source。',
      '首页直接进入曲库，并支持按歌曲下载 Runtime。',
      '补齐 MyKr 品牌字段与正式安装图标。',
    ],
  },
  {
    version: '0.8.3',
    date: '2026-08-23',
    commit: 'e579d61',
    level: 'patch',
    title: '桌面全曲播放器可见性修复',
    summary: '修复桌面布局中全曲播放器可能被内容遮挡的问题。',
    changes: ['让 Full Song 播放器在桌面端保持可见。'],
  },
  {
    version: '0.8.2',
    date: '2026-08-22',
    commit: '5acedff',
    level: 'patch',
    title: '旧学习状态边界修复',
    summary: '把旧 Resume 数据与近期学习状态分开处理，避免迁移信息污染当前产品壳。',
    changes: ['识别 legacy resume，并在不改写旧数据的情况下提供可用的继续学习入口。'],
  },
  {
    version: '0.8.1',
    date: '2026-08-22',
    commit: '9294ca5',
    level: 'patch',
    title: '旧 Resume 识别修复',
    summary: '修复历史学习记录不能被当前曲库识别的问题。',
    changes: ['为旧格式练习记录增加兼容读取路径。'],
  },
  {
    version: '0.8.0',
    date: '2026-08-22',
    commit: '8365396',
    level: 'minor',
    title: '中文产品壳与移动工作台',
    summary: '完成中文曲库、Resume、移动端工作台和产品级歌曲入口收口。',
    changes: [
      '首页支持继续学唱与旧学习状态迁移。',
      'Practice 独立滚动，Full Song 使用固定播放器。',
      '修正移动端歌词层级与播放焦点同步。',
    ],
  },
  {
    version: '0.7.0',
    date: '2026-08-22',
    commit: '169986c',
    level: 'minor',
    title: '讲解工作台',
    summary: '加入 Feature 文章、原地歌词引用和讲解工作台。',
    changes: [
      'Feature 支持结构化文章与歌词引用。',
      '讲解中的歌词引用可以 bounded playback。',
      '歌词引用可以把用户带回对应 Practice Unit。',
    ],
  },
  {
    version: '0.6.2',
    date: '2026-08-21',
    commit: 'da13211',
    level: 'patch',
    title: '全曲歌词触摸跟随修复',
    summary: '修正移动端触摸歌词时的跟随和播放切换语义。',
    changes: ['触摸歌词后保持当前句、播放位置和滚动焦点一致。'],
  },
  {
    version: '0.6.1',
    date: '2026-08-21',
    commit: '4b2c3e7',
    level: 'patch',
    title: '全曲移动播放器首屏修复',
    summary: '让移动端进入全曲模式后可以直接看到核心播放器。',
    changes: ['调整移动端歌曲任务导航与播放器首屏布局。'],
  },
  {
    version: '0.6.0',
    date: '2026-08-21',
    commit: '8c0fa85',
    level: 'minor',
    title: '全曲连续歌词播放器',
    summary: '建立全曲连续歌词工作区、当前句跟随和学习段跳转。',
    changes: [
      '支持全曲连续播放、当前句高亮和移动播放器。',
      '支持从全曲模式跳入 Practice Unit。',
    ],
  },
  {
    version: '0.5.0',
    date: '2026-08-21',
    commit: 'a5c8f48',
    level: 'minor',
    title: '高级 Practice 能力',
    summary: '完成范围、速度、Ramp、Shadow 与个人 Timing 的练习闭环。',
    changes: [
      '建立 Practice Scope 与速度控制。',
      '加入 Ramp、Shadow 和 Personal Timing Override。',
    ],
  },
  {
    version: '0.4.2',
    date: '2026-08-21',
    commit: 'a56d099',
    level: 'patch',
    title: '严格模式学唱修复',
    summary: '修复严格模式下学唱会话无法继续播放的问题。',
    changes: ['让练习会话在 React 严格模式下保持有效。'],
  },
  {
    version: '0.4.1',
    date: '2026-08-20',
    commit: '4124273',
    level: 'patch',
    title: '学唱移动布局与暂停语义修复',
    summary: '修正移动端学唱布局，以及暂停后继续播放的语义。',
    changes: ['让移动端练习控件保持可达，并正确区分暂停和继续。'],
  },
  {
    version: '0.4.0',
    date: '2026-08-20',
    commit: '57bb840',
    level: 'minor',
    title: 'Practice Unit 学唱工作台',
    summary: '建立 Practice contract、学习状态与移动端学唱纵向切片。',
    changes: [
      'Runtime 开始消费 Practice Unit。',
      '加入学习状态与移动端练习布局。',
    ],
  },
  {
    version: '0.3.2',
    date: '2026-08-19',
    commit: '6a04fa7',
    level: 'patch',
    title: '结束播放与 Theme 身份修复',
    summary: '收敛结束播放完成态，并修正视觉模式身份在边界状态下的表现。',
    changes: ['修复 EOF completion 和 Theme identity 的边界。'],
  },
  {
    version: '0.3.1',
    date: '2026-08-19',
    commit: 'eb405aa',
    level: 'patch',
    title: '视觉模式紧凑布局修复',
    summary: '修正 Theme identity 与紧凑布局中的内容溢出。',
    changes: ['收敛视觉模式身份和 compact overflow。'],
  },
  {
    version: '0.3.0',
    date: '2026-08-19',
    commit: 'cb638dd',
    level: 'minor',
    title: 'PWA 与视觉模式体验',
    summary: '建立可离线 Runtime caching，并完成 Focus、Immersive 与多视觉模式的初代体验。',
    changes: [
      '加入离线 Runtime caching 与安装生命周期。',
      '完成三种视觉模式的响应式与无障碍整合。',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-08-18',
    commit: '2e808d5',
    level: 'minor',
    title: 'Timeline Debugger 内容生产闭环',
    summary: '建立音频身份、Timeline Debugger 和内容生产导出工作流。',
    changes: [
      '支持 Occurrence / Section timing 校准。',
      '支持 Timeline 导出与内容质量检查。',
    ],
  },
  {
    version: '0.1.1',
    date: '2026-08-18',
    commit: 'ed4573e',
    level: 'patch',
    title: 'Song Edition 播放边界修复',
    summary: '收敛首个歌曲页面的 consumer 状态边界，避免播放状态在切换时漂移。',
    changes: ['修复 Song Edition consumer 的状态边界。'],
  },
  {
    version: '0.1.0',
    date: '2026-08-18',
    commit: 'fc4a9c2',
    level: 'minor',
    title: 'Runtime 与 Song Edition 基础',
    summary: '建立 Library runtime、Audio Engine、基础歌词播放和首个 Song Edition 页面。',
    changes: [
      '建立 Library source / compiler / runtime model。',
      '建立 Audio Engine、Timeline resolver 与基础歌词播放。',
    ],
  },
]
